/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PC-334_R-419M
 */
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
public final class Contact extends javax.swing.JFrame {
    String ID,NAME,ADDRESS,PHONE;
    
    //All connections
        Connection con_shohag=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","SHOHAG","007");
        Connection con_sadiya=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","SADIYA","123");
        Connection con_kajol=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","KAJOL","123");
        Connection con_bina=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","BINA","123");
        
        //All statements
        Statement st_shohag=con_shohag.createStatement();
        Statement st_sadiya=con_sadiya.createStatement();
        Statement st_kajol=con_kajol.createStatement();
        Statement st_bina=con_bina.createStatement();
        
        ResultSet rs_shohag = null;
        ResultSet rs_sadiya = null;
        ResultSet rs_kajol = null;
        ResultSet rs_bina = null;
        
        String query="Select ID,NAME, ADDRESS, PHONE from ENAME";
    /**
     * Creates new form doctor
     * @throws java.sql.SQLException
     */
    public Contact() throws SQLException {
        initComponents();
        fetch();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        idFeild = new javax.swing.JTextField();
        nameFeild = new javax.swing.JTextField();
        addressFeild = new javax.swing.JTextField();
        mobileFeild = new javax.swing.JTextField();
        idlabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        SaveButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Database = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        DatabaseSadiya = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        DatabaseKajol = new javax.swing.JTable();
        DeleteButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        DatabaseBina = new javax.swing.JTable();
        javax.swing.JLabel phoneLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        EXIT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), new javax.swing.border.MatteBorder(null)));
        mainPanel.setForeground(new java.awt.Color(0, 204, 204));

        idFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFeildActionPerformed(evt);
            }
        });

        nameFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFeildActionPerformed(evt);
            }
        });

        idlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id.JPG"))); // NOI18N

        NameLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/name.JPG"))); // NOI18N

        addressLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/address.JPG"))); // NOI18N
        addressLabel.setToolTipText("");

        SaveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Save-Icon.png"))); // NOI18N
        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        Database.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Database);

        DatabaseSadiya.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(DatabaseSadiya);

        DatabaseKajol.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(DatabaseKajol);

        DeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete_button.png"))); // NOI18N
        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        UpdateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update.png"))); // NOI18N
        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        DatabaseBina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(DatabaseBina);

        phoneLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/phone.JPG"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contact.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dhaka.JPG"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Comilla.JPG"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jessore.JPG"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gazipur.JPG"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contactSoft.JPG"))); // NOI18N

        EXIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        EXIT.setText("EXIT");
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addressFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(mainPanelLayout.createSequentialGroup()
                                    .addGap(85, 85, 85)
                                    .addComponent(idlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(NameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(phoneLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mobileFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(nameFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(idFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(DeleteButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(UpdateButton)))))
                .addGap(81, 81, 81)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(334, 334, 334))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(70, 70, 70)
                .addComponent(EXIT)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(EXIT)))
                .addGap(26, 26, 26)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nameFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addressFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mobileFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(SaveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DeleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UpdateButton)))
                .addContainerGap(485, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2607, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void idFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFeildActionPerformed
    
    public void fetch(){
        try{
            
            rs_shohag=st_shohag.executeQuery(query);
            rs_sadiya=st_sadiya.executeQuery(query);
            rs_kajol=st_kajol.executeQuery(query);
            rs_bina=st_bina.executeQuery(query);
            
            Database.setModel(DbUtils.resultSetToTableModel(rs_shohag));
            DatabaseSadiya.setModel(DbUtils.resultSetToTableModel(rs_sadiya));
            DatabaseKajol.setModel(DbUtils.resultSetToTableModel(rs_kajol));
            DatabaseBina.setModel(DbUtils.resultSetToTableModel(rs_bina));
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void delete() throws SQLException{
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            ID=idFeild.getText();
            NAME=nameFeild.getText();
            ADDRESS=addressFeild.getText();
            PHONE=mobileFeild.getText();
            
            String deleteQuery;
            deleteQuery = "DELETE from ENAME where id='"+ID+"'";
            
            switch (ADDRESS) {
                case "Dhaka":
                    st_shohag.executeUpdate(deleteQuery);
                    JOptionPane.showMessageDialog(null, "Successfully Deleted!");
                    break;
                case "Comilla":
                    st_sadiya.executeUpdate(deleteQuery);
                    JOptionPane.showMessageDialog(null, "Successfully Deleted!");
                    break;
                case "Jessore":
                    st_bina.executeUpdate(deleteQuery);
                    JOptionPane.showMessageDialog(null, "Successfully Deleted!");
                    break;
                case "Gazipur":
                    st_kajol.executeUpdate(deleteQuery);
                    JOptionPane.showMessageDialog(null, "Successfully Deleted!");
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Wrong Address!!");
            }
            
            
            
        }catch(ClassNotFoundException e){
           JOptionPane.showMessageDialog(null, e); 
        }
        fetch();
    }
    
    public void update() throws SQLException{
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            ID=idFeild.getText();
            NAME=nameFeild.getText();
            ADDRESS=addressFeild.getText();
            PHONE=mobileFeild.getText();
            
            String updateQuery;
            updateQuery = "UPDATE ENAME SET Name='"+NAME+"',address='"+ADDRESS+"',phone='"+PHONE+"' where id='"+ID+"'";
            
            
            switch (ADDRESS) {
                case "Dhaka":
                    st_shohag.executeUpdate(updateQuery);
                    JOptionPane.showMessageDialog(null, "Successfully Updated!");
                    break;
                case "Comilla":
                    st_sadiya.executeUpdate(updateQuery);
                    JOptionPane.showMessageDialog(null, "Successfully Updated!");
                    break;
                case "Jessore":
                    st_bina.executeUpdate(updateQuery);
                    JOptionPane.showMessageDialog(null, "Successfully Updated!");
                    break;
                case "Gazipur":
                    st_kajol.executeUpdate(updateQuery);
                    JOptionPane.showMessageDialog(null, "Successfully Updated!");
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Wrong Address!!");
            }
            
            
            
        }catch(ClassNotFoundException e){
           JOptionPane.showMessageDialog(null, e); 
        }
        fetch();
        emptyFeild();
    }
    
    private void emptyFeild(){
        idFeild.setText(null);
        nameFeild.setText(null);
        addressFeild.setText(null);
        mobileFeild.setText(null);
    }
    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            
            
            ID=idFeild.getText();
            NAME=nameFeild.getText();
            ADDRESS=addressFeild.getText();
            PHONE=mobileFeild.getText();
            
            String saveQuery;
            saveQuery = "insert into ENAME(ID,NAME,ADDRESS,PHONE) values ('"+ID+"','"+NAME+"','"+ADDRESS+"','"+PHONE+"')";
            switch (ADDRESS) {
                case "Dhaka":
                    st_shohag.executeUpdate(saveQuery);
                    JOptionPane.showMessageDialog(null, "Successfully Saved!");
                    break;
                case "Comilla":
                    st_sadiya.executeUpdate(saveQuery);
                    JOptionPane.showMessageDialog(null, "Successfully Saved!");
                    break;
                case "Jessore":
                    st_bina.executeUpdate(saveQuery);
                    JOptionPane.showMessageDialog(null, "Successfully Saved!");
                    break;
                case "Gazipur":
                    st_kajol.executeUpdate(saveQuery);
                    JOptionPane.showMessageDialog(null, "Successfully Saved!");
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Wrong Address!!");
            }
            
//            System.out.println("Shohag DATABASE:");
//            String query = "select id,name,address from ENAME";
//            ResultSet rs_shohag=st_shohag.executeQuery(query);
//            while(rs_shohag.next()){
//            System.out.println(rs_shohag.getString(1)+" "+rs_shohag.getString(2)+" "+rs_shohag.getString(3));
//            }
              
              

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Contact.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        fetch();
        emptyFeild();
        
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        try {
            
        delete();
        } catch (SQLException ex) {
            Logger.getLogger(Contact.class.getName()).log(Level.SEVERE, null, ex);
        }
        fetch();
        emptyFeild();
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        try {
            update();
        } catch (SQLException ex) {
            Logger.getLogger(Contact.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void nameFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFeildActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        System.exit(0x0);
    }//GEN-LAST:event_EXITActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Contact().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(Contact.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Database;
    private javax.swing.JTable DatabaseBina;
    private javax.swing.JTable DatabaseKajol;
    private javax.swing.JTable DatabaseSadiya;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton EXIT;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JButton SaveButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JTextField addressFeild;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField idFeild;
    private javax.swing.JLabel idlabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField mobileFeild;
    private javax.swing.JTextField nameFeild;
    // End of variables declaration//GEN-END:variables
}
